name: Deploy para S3 com aprovação

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Aprovação + Deploy para o S3
    runs-on: ubuntu-latest

    # Nome do ambiente configurado no GitHub (Settings > Environments)
    environment:
      name: production
      url: https://conchayoro-iha.s3.us-east-1.amazonaws.com/index.html

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar o AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Fazer deploy dos ficheiros para o S3
        run: |
          aws s3 sync ./public s3://conchayoro-iha --delete
